### ISSUE TITLE
matching directory names

### ISSUE THREAD

**Issue by fred0r** [fdett/jellyfin-ignore#1]
jellyfin has some built-in option for [dirs](https://jellyfin.org/docs/general/server/media/excluding-directory/), but it depends on altering the filesystem for each subdir to get ignored.
i would like to ignore directorynames recursively with your plugin and tried `/**/[SAMPLE]`, but even after a rescan these are still shown.
after looking to the examples you linked it seems, that your ignore 'only' matches filenames.
could you pls also add ignoring directory names?

**Comment by fdett** [comment]
You should be able to do that by adapting the pattern to ignore.
For example: `basedir/**/*.*` would ignore everything under basedir

You can check out more examples here (it's the library that is being used under the hood): https://github.com/dazinator/DotNet.Glob
